$( "#call" ).click(function() {
  event.preventDefault();

$("#main-container").replaceWith(
    '<section class="content">'
      +'<div class="container-fluid">'
        +'<div class="row">'
          +'<div class="col-12">'


            +'<div class="card">'
              +'<div class="card-header">'
                +'<h3 class="card-title col-10">Call Logs</h3>'
                +'<button type="button" data-toggle="modal" href="#sync" class="btn btn-primary col-2">Actualizar <i class="fa fa-sync"></i></button>'
              +'</div>'
              +'<!-- /.card-header -->'
              +'<div class="card-body">'
              +'<table id="call_log" class="table table-bordered table-hover">'
                +'<thead>'
                  +'<tr>'
                   + '<th>Name</th>'
                   + '<th>Phone Number</th>'
                   + '<th>Type</th>'
                   + '<th>Duration</th>'
                   + '<th>Date</th>'
                  +'</tr>'
                +'</thead>'
               +'<tbody>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                  +'<tr>'
                  +'  <td>H. K. Skip Pita </td>'
                  +'  <td>+56 930139035'
                  +'  </td>'
                  +'  <td>Outgoing</td>'
                  +'  <td>01:24:03</td>'
                  +'  <td>2021-02-06 15:37:28</td>'
                  +'</tr>'
                +'</tbody>'
                +'<tfoot>'
                  +'<tr>'
                   + '<th>Name</th>'
                   + '<th>Phone Number</th>'
                   + '<th>Type</th>'
                   + '<th>Duration</th>'
                   + '<th>Date</th>'
                  +'</tr>'
                +'</tfoot>'
                +'</table>'
              +'</div>'
              +'<!-- /.card-body -->'
           
           +'</div>'
        +'</div>'
      +'</div>'
    +'</section>'

);


$('#call_log').dataTable();



});




